name: Build Bauantibotsentryproxy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: |
          git config --global user.name "GitHub Actions"
          ./bauantibotsentryproxy p
          ./bauantibotsentryproxy b
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bauantibotsentryproxy jar
          path: /Bauantibotsentryproxy-proxy/proxy/target/bauantibotsentryproxy-*.jar
