name: Build Bauantibotsentryproxy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./bauantibotsentryproxy p
      - name: build
        run: ./bauantibotsentryproxy b
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bauantibotsentryproxy
          path: ./Bauantibotsentryproxy-proxy/proxy/target/bauantibotsentryproxy-proxy-*.jar
